# Generated by Django 3.1.5 on 2021-01-20 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_category', models.CharField(max_length=100)),
                ('total_question', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('test_password', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.TextField()),
                ('choice_1', models.TextField()),
                ('choice_2', models.TextField()),
                ('choice_3', models.TextField()),
                ('choice_4', models.TextField()),
                ('correct_choice', models.CharField(max_length=20)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rateme.tests')),
            ],
        ),
    ]
