# Generated by Django 3.1.5 on 2021-01-22 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=100)),
                ('test_started', models.DateTimeField()),
                ('test_ended', models.DateTimeField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rateme.tests')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_value', models.IntegerField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rateme.question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rateme.tests')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rateme.usermapper')),
            ],
        ),
    ]
