# Generated by Django 3.1.5 on 2021-01-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0002_submission_usermapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermapper',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usermapper',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
