# Generated by Django 3.1.5 on 2021-01-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0003_auto_20210122_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermapper',
            name='test_ended',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usermapper',
            name='test_started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
