# Generated by Django 3.1.5 on 2021-01-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0004_auto_20210122_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermapper',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
