# Generated by Django 3.1.5 on 2021-01-23 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rateme', '0005_usermapper_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateme.tests'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateme.question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateme.tests'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateme.usermapper'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermapper',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateme.tests'),
        ),
    ]
